spring:
  application:
    name: player-service
  cloud:
    nacos:
      discovery:
        server-addr: 34.130.59.222
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://34.130.59.222:3306/player-service?createDatabaseIfNotExist=true
    username: root
    password: rootpwd@cas-735
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: always
  rabbitmq:
    host: 34.130.59.222
    port: 5672
    username: mq-cas-735
    password: mq-cas-735
    geo:
      exchange: geo-service
      queue: player->geo
  data:
    redis:
      host: 34.130.59.222
      port: 6379
      password: redis@cas-735

server:
  port: 9000
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /api.html