version: "2.4"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "8080:8080"
    networks:
      - srvnet
    volumes:
      - ./api-gateway/Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped

  player:
    image: macrun/player-service:latest
    build:
      context: ./player-service
    networks:
      - srvnet
    container_name: player
    restart: unless-stopped

  hrm:
    image: macrun/hrm-service:latest
    build:
      context: ./hrm-service
    networks:
      - srvnet
    container_name: hrm
    restart: unless-stopped

  game:
    image: macrun/game-service:latest
    build:
      context: ./game-service
    networks:
      - srvnet
    container_name: game
    restart: unless-stopped

  geo:
    image: macrun/geo-service:latest
    build:
      context: ./geo-service
    networks:
      - srvnet
    container_name: geo
    restart: unless-stopped

  challenge:
    image: macrun/challenge-service:latest
    build:
      context: ./challenge-service
    networks:
      - srvnet
    container_name: challenge
    restart: unless-stopped

networks:
  srvnet:
    driver: bridge
