version: "2.4"

services:
  caddy:
    image: caddy:latest
    container_name: caddy
    ports:
      - "8080:8080"
    volumes:
      - ./api-gateway/Caddyfile:/etc/caddy/Caddyfile
    restart: unless-stopped

  player:
    image: macrun/player-service:latest
    build:
      context: ./player-service
    container_name: player
    restart: unless-stopped

  hrm:
    image: macrun/hrm-service:latest
    build:
      context: ./hrm-service
    container_name: hrm
    restart: unless-stopped

  game:
    image: macrun/game-service:latest
    build:
      context: ./game-service
    container_name: game
    restart: unless-stopped
