server:
  ip:
  port: 9090

discovery:
  host: 34.130.59.222 #127.0.0.1
  port: 8848
  service: game-service

rabbitmq:
  url: amqp://mq-cas-735:mq-cas-735@34.130.59.222:5672/

redis:
  host: 34.130.59.222
  port: 6379
  password: redis@cas-735
