spring:
  application:
    name: challenge-service
  cloud:
    nacos:
      discovery:
        server-addr: nacos
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/challenge-service?createDatabaseIfNotExist=true
    username: root
    password: rootpwd@cas-735
  jpa:
    hibernate:
      ddl-auto: create
    show-sql: true
    defer-datasource-initialization: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: always
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: mq-cas-735
    password: mq-cas-735
    exchange: challenge-service
    queue: game->challenge
  data:
    redis:
      host: redis
      port: 6379
      password: redis@cas-735

server:
  port: 9001
