server:
  ip:
  port: 9090

discovery:
  host: 34.130.59.222 #127.0.0.1
  port: 8848
  service: game-service

rabbitmq:
  url: amqp://guest:guest@34.130.59.222:5672/

redis:
  host: 34.130.59.222
  port: 6379
