spring:
  main:
    allow-circular-references: true
  application:
    name: hrm-service
  cloud:
    nacos:
      discovery:
        server-addr: nacos
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://mariadb:3306/player-service?createDatabaseIfNotExist=true
    username: root
    password: rootpwd@cas-735
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: always
  rabbitmq:
    host: rabbitmq
    port: 5672
    username: mq-cas-735
    password: mq-cas-735
    exchange: hrm-service
    game:
      exchange: game-service
      queue: hrm->game
  data:
    redis:
      host: redis
      port: 6379
      password: redis@cas-735

server:
  port: 9500
springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /hrm-swagger/index.html
