spring:
  application:
    name: hrm-service
  cloud:
    nacos:
      discovery:
        server-addr: 34.130.59.222
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    url: jdbc:mariadb://34.130.59.222:3306/player-service?createDatabaseIfNotExist=true
    username: root
    password: admin
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true
  sql:
    init:
      mode: always
  rabbitmq:
    host: 34.130.59.222
    port: 5672
    username: guest
    password: guest
    exchange: hrm-service
    game:
      exchange: game-service
      queue: hrm->game
  data:
    redis:
      host: 34.130.59.222
      port: 6379

server:
  port: 9500

